"""Init

Revision ID: 4b1cb9a9c793
Revises: 
Create Date: 2022-09-23 12:23:55.275638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1cb9a9c793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kbs',
    sa.Column('kbs_id', sa.Integer(), nullable=False),
    sa.Column('kbs_desc', sa.String(length=1664), nullable=True),
    sa.Column('kbs_resolution', sa.String(length=1664), nullable=True),
    sa.Column('kbs_tag', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('kbs_id')
    )
    op.create_index(op.f('ix_kbs_kbs_desc'), 'kbs', ['kbs_desc'], unique=False)
    op.create_index(op.f('ix_kbs_kbs_resolution'), 'kbs', ['kbs_resolution'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_kbs_kbs_resolution'), table_name='kbs')
    op.drop_index(op.f('ix_kbs_kbs_desc'), table_name='kbs')
    op.drop_table('kbs')
    # ### end Alembic commands ###
