apiVersion: v1
kind: Secret
metadata:
  name: act-bot-secret
  namespace: equator-default-performance
type: Opaque 
data: 
  username: dHV5ZW4udHJhbmR1eQ==
  password: SDBkam5hX20zbnV3bmtzZDk=
  sonar_token: MDBhMDZhY2VhNjMwNmY4YTdlOTNmMTMwYjkxMjkwMzc2MDIwN2Y2OA==